language: java

sudo: true

services:
  - xvfb

jdk:
  - openjdk13

env:
  global:
    - CODECOV_TOKEN=d3d98ab1-fccc-4c2c-9709-40527d447957

branches:
  except:
    - dev

before_script:
  - "export DISPLAY=:99.0"

after_success:
  - bash <(curl -s https://codecov.io/bash)
